#!/usr/bin/env node
/**
 * Generate the inline SVG icons the site uses, from the icon packages, into
 * src/app/core/icons/icons.generated.ts (not tracked: the build writes it, d-115f49-9700ab).
 *
 * The site names icons by string, in templates and in the content JSON:
 *   devicon-<name>-<variant>   -> devicon/icons/<name>/<name>-<variant>.svg
 *   fa-<style>-<name>          -> @fortawesome/fontawesome-free/svgs/<style>/<name>.svg
 * Only the names found in src/ are generated, so an icon costs nothing until it is used, and a name
 * whose file does not exist fails the build here instead of rendering an empty box.
 * Colours are removed: an icon is drawn in `currentColor`, as the icon fonts it replaces were.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/app/core/icons/icons.generated.ts');
const NAME = /\b(devicon-[a-z0-9]+-(?:plain|original|line)(?:-wordmark)?|fa-(?:solid|regular|brands)-[a-z0-9-]+)\b/g;

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : /\.(html|ts|json)$/.test(n) && !n.endsWith('.spec.ts') && p !== OUT ? [p] : [];
  });
}

function source(name) {
  if (name.startsWith('devicon-')) {
    const [, icon, variant] = name.match(/^devicon-([a-z0-9]+)-(.+)$/);
    return join(ROOT, 'node_modules/devicon/icons', icon, `${icon}-${variant}.svg`);
  }
  const [, style, icon] = name.match(/^fa-(solid|regular|brands)-(.+)$/);
  return join(ROOT, 'node_modules/@fortawesome/fontawesome-free/svgs', style, `${icon}.svg`);
}

/** One SVG, recoloured to currentColor and sized by the surrounding font, like an icon font glyph. */
function inline(svg) {
  return svg
    .replace(/<\?xml[^>]*>|<!DOCTYPE[^>]*>/g, '')
    .replace(/\s(fill|stroke)="(?!none)[^"]*"/g, '')
    .replace(/\sstyle="[^"]*"/g, '')
    .replace(/<style[^]*?<\/style>/g, '')
    .replace(/\s(width|height)="[^"]*"/g, '')
    .replace(/<svg\b/, '<svg width="1em" height="1em" fill="currentColor" aria-hidden="true" focusable="false"')
    .replace(/\s+/g, ' ')
    .trim();
}

const names = [...new Set(walk(join(ROOT, 'src')).flatMap((f) => [...readFileSync(f, 'utf8').matchAll(NAME)].map((m) => m[1])))].sort();
const missing = names.filter((n) => !existsSync(source(n)));
if (missing.length) {
  console.error(`icons: no SVG for ${missing.join(', ')}`);
  process.exit(1);
}

const entries = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(inline(readFileSync(source(n), 'utf8')))},`);
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by tools/icons.mjs from the devicon (MIT) and Font Awesome Free (icons CC BY 4.0) packages.
// Do not edit: run \`node tools/icons.mjs\`, which every build, serve and test script runs first.
/*! Font Awesome Free icons by Fonticons, Inc. - https://fontawesome.com/license/free (CC BY 4.0). Devicon - https://github.com/devicons/devicon (MIT). */
export const ICONS: Record<string, string> = {
${entries.join('\n')}
};
`,
);
console.log(`icons: ${names.length} written to ${OUT.slice(ROOT.length + 1)}`);
