#!/usr/bin/env node
/**
 * Convert the blog's markdown posts into src/app/blog/posts.generated.ts (not tracked: the build
 * writes it, d-115f49-9700ab), so a post is part of the bundle and costs no request.
 *
 * A post is blog/<slug>.md and is served at /blog/<slug>. Its front matter is flat `key: value`
 * lines; `title`, `description` and `published` are required (`audit:posts` checks them before any
 * install), and a post with `published: false` is left out of the build entirely.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/app/blog/posts.generated.ts');
const REQUIRED = ['title', 'description', 'published'];

function parse(file) {
  const text = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const match = text.match(/^---\n([^]*?)\n---\n?([^]*)$/);
  if (!match) throw new Error(`${file}: no front matter`);
  const meta = Object.fromEntries(
    match[1].split('\n').filter((l) => l.trim()).map((l) => {
      const at = l.indexOf(':');
      const value = l.slice(at + 1).trim().replace(/^(['"])(.*)\1$/, '$2');
      return [l.slice(0, at).trim(), value === 'true' ? true : value === 'false' ? false : value];
    }),
  );
  const missing = REQUIRED.filter((k) => !(k in meta));
  if (missing.length) throw new Error(`${file}: front matter lacks ${missing.join(', ')}`);
  return {
    slug: basename(file, '.md'),
    title: String(meta.title),
    description: String(meta.description),
    published: meta.published === true,
    html: marked.parse(match[2], { async: false }),
  };
}

const dir = join(ROOT, 'blog');
const posts = readdirSync(dir).filter((n) => n.endsWith('.md')).sort().map((n) => parse(join(dir, n)));
const published = posts.filter((p) => p.published).map(({ published, ...post }) => post);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by tools/posts.mjs from blog/*.md. Do not edit: every build, serve and test script runs it.
import { Post } from './post';

export const POSTS: Post[] = ${JSON.stringify(published, null, 2)};
`,
);
console.log(`posts: ${published.length} of ${posts.length} published, written to ${OUT.slice(ROOT.length + 1)}`);
